pyobjus/pyobjus.pyx, pyobjus/pyobjus_conversions.pxi, pyobjus/runtime.pxi
Since ARM64 introduction (iOS 8), delegate implementation are using the "slow" path of objective-c.
We are not able anymore to declare a variadic function for responding to any kind of selector, as the ARM64 convention call differ from other platform, and va_start/arg/end doesn't work on ARM64 as well.
Instead, we are manually using forwardInvocation:, named as the "slow" path.
Ref: http://arigrant.com/blog/2013/12/13/a-selector-left-unhandled
The idea is, when there is no implementation of a selector on the target, objc will forward the call to a forwardInvocation: selector on the target, containing the original invocation and parameters in a NSInvocation. For pyobjus, it's separated in 3 steps:
- respondsToSelector: > the target class must indicate which selector is implemented in …
=> fix ARM64 delegate

pyobjus/_runtime.h
We had the same 'dl_open error on foundation' as those below. This seems to fix it.
https://groups.google.com/forum/#!msg/kivy-dev/n7bDbBsAVuQ/L9WNZp-FEQAJ
closes #22
=> Add fallback path for Foundation lookup

pyobjus/pyobjus_conversions.pxi
Pass bytes to `void*` the same as we do to `char*`. This fixes an issue with calling `NSData.dataWithBytes_length_(bytestr, len(bytestr))` and ending up with a data object which doesn't contain the correct data.
Technically, the arg type is `^v` and the `^` has already been stripped off, so the type passed to `convert_py_arg_to_cy` is just `v` - void rather than a void pointer. However, you can never pass a void, only a void pointer, so it's safe to assume that the original arg type was `^v`.
=> fix passing bytes as void*

.travis.yml, Makefile, pyobjus/__init__.py, pyobjus/debug.py, pyobjus/dylib_manager.py, pyobjus/ffi.pxi, pyobjus/objc_cy_types.pxi, pyobjus/objc_py_types.py, pyobjus/pyobjus.pyx, pyobjus/pyobjus_conversions.pxi, pyobjus/pyobjus_types.pxi, pyobjus/type_enc.pxi, tests/test_carray.py, tests/test_dereference.py, tests/test_nsobject.py, tests/test_nsstring.py, tests/test_nsvalue.py, tests/test_properties.py, tests/test_union.py, tests/test_unknown_types.py
This PR make pyobjus works on Python 3, as well as Python 2.
It also fixes few tests, and deactivate the one that segfault directly or later (from a long time, so it's not something that the PR was intented to solve).
The unit tests are working on both Python 2.7.13 and Python 3.6.6, using Cython 0.28.1. It also now use pytest as runner and sometimes in unit test for approximation functions.
There is few API changes:
- All the C string returns bytes strings. Never unicode.
- NSString and related with the functions UTF8String_ returns unicode string (Python 2 impacted here)
- CArrayCount special attribute for retrieving the number of element in a pointer is removed, and adopt a more general usage with a ctypes.c_uint (look at the tests/test_carray.py, it make sense). It is a little bit …
=> Support for Python 3

pyobjus/pyobjus.pyx
I used pretty much all of these extra messages in tracking down #49 so it may be nice (for the next bug) if they are there.
Obviously, they do nothing unless `PYOBJUS_DEBUG=1`
=> add some extra logging

pyobjus/pyobjus.pyx, tests/test_delegate.py
Pyobjus has the ability to specify a python class as a delegate for an Objective C call by using the `@prototol` decorator.
However, this will crash on a MacOS or IOS target if the delegate is referenced a second time (say by instantiating an Widget that wraps an Objective C method in two different places)
The bug occurs when `convert_py_to_nsobject` invokes
https://github.com/kivy/pyobjus/blob/f84a58e9b301bffad508e13ccade6c0cdf79e2a3/pyobjus/pyobjus_conversions.pxi#L452
This dynamically creates an Objective C class here:
https://github.com/kivy/pyobjus/blob/f84a58e9b301bffad508e13ccade6c0cdf79e2a3/pyobjus/pyobjus.pyx#L933-L934
Unfortunately, this call fails (and returns `nil`) when called a second time with the same c_cls_name.
Rrom the docs: 
> Return Value: The new class, or `Nil` if …
=> Fix delegate instance

pyobjus/type_enc.pxi
This PR adds type encoding `b'x?'` (unknown type pointer)
=> Add type encoding for unknown type

pyobjus/type_enc.pxi
This case removed is already handled further up the "if" block added in this PR.
https://github.com/kivy/pyobjus/pull/56/files#diff-f191812f25d305f4237695cde985839aR159
=> Remove case already covered in previous elif

pyobjus/pyobjus_types.pxi, tests/test_nsarray.py
=> Function `objc_arr` would crash with empty arrays.

pyobjus/_runtime.h, pyobjus/common.pxi, pyobjus/pyobjus.pyx
The previous `ARCH!= 'arm64'` implementation for checking if we were building for `arm64` worked great until **python3.10**, which by default builds a  `universal2` wheel that contains binaries for both `x86_64` and `arm64` also on `x86_64` macs.
WARNING: I didn't have the chance to test on runtime if a call to `objc_msgSend_stret` works fine, and the tests probably need to be improved and have to run on CI.
Fixes issue #81
=> Fixes universal2 build

docs/source/core_tutorials.rst, docs/source/pyobjus_ios.rst, examples/pointer_to_type.py, examples/unions.py, examples/unknown_type.py
There are small typos in:
- docs/source/core_tutorials.rst
- docs/source/pyobjus_ios.rst
- examples/pointer_to_type.py
- examples/unions.py
- examples/unknown_type.py
Fixes:
- Should read `something` rather than `sommething`.
- Should read `screenshot` rather than `screenshoot`.
- Should read `internally` rather than `internaly`.
- Should read `enough` rather than `enought`.
- Should read `union` rather than `unoin`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: Fix a few typos

.github/workflows/deploy.yml
Drops old token which doesn't work and we don't need anymore.
=> Fix github release token

.github/workflows/python-package.yml
- Same of https://github.com/kivy/kivy/pull/7885
- https://github.com/actions/runner/releases/tag/v2.292.0 now supports Apple Silicon natively. 🥳
- The run_wrapper that was enforcing arm64 on top of a x86_64 process is now un-needed.
- There's a pending PR in actions/python-versions which is expected to introduce support for universal2 versions of Python, so hopefully, we will be able to rely on actions/setup-python also for our self hosted runner in a while..
=> Our self-hosted Apple Silicon runner now has been migrated to actions/runner v2.292.0 which now supports arm64 natively

README.md
Update the support info to be consistent with other Kivy projects.
=> Add Discord and remove IRC from support channels

.github/workflows/python-package.yml, setup.py
- Updates the supported Python version list to be consistent with other Kivy projects (3.7-3.11)
- Add Python 3.11 to the test matrix
=> Add Python 3.11 to test matrix and update supported python versions list

.github/workflows/python-package.yml, pyobjus/pyobjus.pyx, pyobjus/pyobjus_types.pxi, setup.py
Took inspiration from https://github.com/kivy/pyjnius/pull/669.
- Adds support for Cython >= 3 (while keeping support for Cython < 3, which is needed to build on `python-for-android` and `kivy-ios`)
=> Add support for Cython >=3 and keep support for Cython < 3

.github/workflows/deploy.yml, .github/workflows/python-package.yml, setup.py
- Adds tests on Python 3.12
- Force `cibuildwheel` to `~=2.16.2`, so it can build `3.12` artifacts and add `cp312-macosx_universal2` to `CIBW_BUILD`
- Update docs
=> Add support for Python 3.12 (tests, wheel, docs)

setup.py
... we will have, once the whole recipe thing will move away from `setup.py build_ext`
=> Fixes the build on `kivy-ios`, as we do not have access to `Cython`

.github/workflows/python-package.yml, setup.py
Removing Python `3.7` as reached EOL on June 27th 2023
=> Remove support for Python `3.7` as reached EOL

objc_classes/test/testlib.m
Recent Xcode versions started to treat `Wincompatible-function-pointer-types` as an error.
Our test code for variadic functions actually takes advantage of this "feature".
This PR disables `-Wincompatible-function-pointer-types` checks on that chunk of code.
Maybe we should rewrite that test code to avoid that in future?
=> Disable `-Wincompatible-function-pointer-types` in `testlib`

pyobjus/pyobjus_conversions.pxi
Seems `Long` keyword no longer exists in python ?
=> Cython now defaults to `language_version=3`, and `long` is not available anymore (was available only in `Py2`)
